"""
    _parse_sub_label(lbl::String) -> NamedTuple{(:country, :sector, :tag)}

Parse a subsegment label of the form `"COUNTRY:SECTOR:TAG"` (e.g., `"A:Primary:Firm"`)
into its structured components.

### Arguments
- `lbl::String` : A subsegment label generated by `make_emrio_twofold()`.

### Returns
- `NamedTuple` with keys:
  - `country::String` : Country code (e.g., `"A"` or `"B"`).
  - `sector::String`  : Sector name (e.g., `"Primary"`).
  - `tag::Symbol`     : Subsegment tag `:Firm` or `:Other`.

### Example
```julia
_parse_sub_label("A:Secondary:Firm")
# → (country = "A", sector = "Secondary", tag = :Firm)
```
"""
_parse_sub_label(lbl::String) = begin
    p = split(lbl, ":")
    (country = p[1], sector = p[2], tag = Symbol(p[3]))
end